WebApp1/WebApp1/Models/CalcModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp1.Models
{
    public class CalcModel
    {
        public readonly int X;
        public readonly int Y;
        public readonly string Add;
        public readonly string Sub;
        public readonly string Mult;
        public readonly string Div;
        public CalcModel(int x, int y, string add, string sub, string mult, string div)
        {
            X = x;
            Y = y;
            Add = add;
            Sub = sub;
            Mult = mult;
            Div = div;
        }
    }
}

WebApp1/WebApp1/Controllers/CalcServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApp1.Models;
using WebApp1.Services;

namespace WebApp1.Controllers
{
    public class CalcServiceController : Controller
    {
        private readonly CalcService _service;

        public CalcServiceController(CalcService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PassUsingModel()
        {
            return View(_service.GetCalcModel());
        }

        public IActionResult PassUsingViewData()
        {
            var model = _service.GetCalcModel();
            ViewData["X"] = model.X;
            ViewData["Y"] = model.Y;
            ViewData["Add"] = model.Add;
            ViewData["Sub"] = model.Sub;
            ViewData["Mult"] = model.Mult;
            ViewData["Div"] = model.Div;
            return View();
        }

        public IActionResult PassUsingViewBag()
        {
            var model = _service.GetCalcModel();
            ViewBag.X = model.X;
            ViewBag.Y = model.Y;
            ViewBag.Add = model.Add;
            ViewBag.Sub = model.Sub;
            ViewBag.Mult = model.Mult;
            ViewBag.Div = model.Div;
            return View();
        }

        public IActionResult AccessServiceDirectly()
        {
            return View();
        }
    }
}

WebApp1/WebApp1/Views/CalcService/AccessServiceDirectly.cshtml
@using WebApp1.Services
@inject CalcService Service
@{
    ViewBag.Title = "AccessServiceDirectly - Backend1";
    var model = Service.GetCalcModel();
}
<h1>AccessServiceDirectly</h1>

<b>Rand value first:</b> @(model.X)
<br />
<b>Rand value second:</b> @(model.Y)
<br />

<b>Add:</b>
<br />
@(model.Add)
<br />

<b>Dif:</b>
<br />
@(model.Sub)
<br />

<b>Mult:</b>
<br />
@(model.Mult)
<br />

<b>Div:</b>
<br />
@(model.Div)
<br />

WebApp1/WebApp1/Views/CalcService/Index.cshtml
@{
    ViewData["Title"] = "Home Page - Backend1";
}

<h1>Calc Service Demonstration</h1>
<ul>
    <li><a asp-controller="CalcService" asp-action="PassUsingModel">Using Model Calc</a></li>
    <li><a asp-controller="CalcService" asp-action="PassUsingViewData">Using ViewData Calc</a></li>
    <li><a asp-controller="CalcService" asp-action="PassUsingViewBag">Using ViewBag Calc</a></li>
    <li><a asp-controller="CalcService" asp-action="AccessServiceDirectly">Using Service Injection Calc</a></li>
</ul>

WebApp1/WebApp1/Views/CalcService/PassUsingModel.cshtml
@model WebApp1.Models.CalcModel
@{
    ViewBag.Title = "PassUsingModel - Backend1";
}

<h1>PassUsingModel</h1>
<b>Rand value first:</b> @Model.X
<br />
<b>Rand value second:</b> @Model.Y
<br />

<b>Add:</b>
<br />
@Model.Add
<br />

<b>Sub:</b>
<br />
@Model.Sub
<br />

<b>Mult:</b>
<br />
@Model.Mult
<br />

<b>Div:</b>
<br />
@Model.Div
<br />

WebApp1/WebApp1/Views/CalcService/PassUsingViewBag.cshtml
@{
    ViewBag.Title = "PassUsingViewBag - Backend1";
}
<h1>PassUsingViewBag</h1>
<b>Rand value first:</b> @ViewBag.X
<br />
<b>Rand value second:</b> @ViewBag.Y
<br />

<b>Add:</b>
<br />
@ViewBag.Add
<br />

<b>Dif:</b>
<br />
@ViewBag.Sub
<br />

<b>Mult:</b>
<br />
@ViewBag.Mult
<br />

<b>Div:</b>
<br />
@ViewBag.Div
<br />

WebApp1/WebApp1/Views/CalcService/PassUsingViewData.cshtml
@{
    ViewBag.Title = "PassUsingViewData - Backend1";
}
<h1>PassUsingViewData</h1>
<b>Rand value first:</b> @ViewData["X"]
<br />
<b>Rand value second:</b> @ViewData["Y"]
<br />

<b>Add:</b>
<br />
@ViewData["Add"]
<br />

<b>Sub:</b>
<br />
@ViewData["Sub"]
<br />

<b>Mult:</b>
<br />
@ViewData["Mult"]
<br />

<b>Div:</b>
<br />
@ViewData["Div"]
<br />

WebApp1/WebApp1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="">Backend1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="CalcService" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Backend1 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>